# Today: Data Wrangling GROUPS!

Choose a team, and then spend some time looking at data.  We want you to explore the data using the techniques we learned this far including:

- Grouping / subsetting / segmentation
- Summary statistics
    - Histograms
    - Plotting
- Slicing
- Cleaning data
    - assessing proper types
    - expected values
    - object converstion
   

At the end of our exploratory analysis, each group will be giving a 10 minute presentation on their findings to the rest of class.

In [3]:
import pandas as pd, numpy as np, seaborn as sns

%matplotlib inline

## Team Alpha Drone

Since the API from `api.dronestre.am` provides data on drone strikes in near real time, this **might** be useful to hold President Obama accountable to his promise of reducing drone strikes.  Your mission, is to explore drone strike data, doing any accomanying research with your analysis, and report back any good summary statistics.

Also, we would like to know:
 - Is this a good source of data?
     - Why / why not?
     
*Politics aside -- let's keep it to what is measurable in our dataset.  This isn't meant to prove or disprove anything.  It's a **fun** dataset to look at moreso than a motivator of political discourse.*

In [4]:
# First we need to fetch some data using Python requests from API
# Read more about Python requests:
# http://docs.python-requests.org/en/master/user/quickstart/

import requests
import pandas as pd
response = requests.get("http://api.dronestre.am/data")
json_data = response.json()
drone_df = pd.DataFrame(json_data['strike'])

In [63]:
drone_df.groupby('target')['injuries', 'children'].sum().sort('injuries', ascending = False)

,injuries,children
target,,
Abu Sulayman al-Jazairi,94,3
,9151695448395211323252735101213672974356657888...,10-1PossiblyYes413PossiblyPossiblyAt least 210...
Maulvi Noor Mohammed,9,
Wali Muhammad Mehsud,7,0
Abdullah Azzam al-Saudi,7,
Niaz Wali,7,
Khalid Habib,7,
Bahram Khan Kochi,7,
Zubair al-Masri,6,
Hafiz Gul Bahadur,534,At least 1
Baitullah Mehsud,5153505745,1
Saifullah,5,
Abu Kasha,5,
Abdul Rehman,4,Possibly
Abu Wafa al-Saudi,4,
Sheikh Yaseen al Somali,4,0-1
Maulvi Nazir?,4,
Maulvi Liaqat,3,69
Abdul Rehman al-Zaman Yemeni?,3,0
Abu Khabab al-Masri,3,3
Ilyas Kashmiri,3,
Maulvi Nazir,230545510420,0-330
Hakimullah Mehsud; Baitullah Mehsud,2,Yes
"Abu Kasha al Iraqi, Saleh al Turki",2,0
Hafiz Sahar Gul,2,4-Mar
Hafiz Gul Bahadar,17,
Hakimullah Mehsud,16,3
Qari Imran,14,
Jalalludin Haqqani,1225,8
Maulvi Nazir; Malang Wazir,10,
Tariq Khan,1,4
Shaykh Issa al-Masri,1,
Baitullah Mehsud ally,1,1
Abu Hamza Rabia,1,32
Nek Mohammed,1,2
Nader al Shaddadi,1,1
Abu Laith al-Libi,1,3
Abu Jihad al-Masri; Abdur Rehman abu Akash,0,
Taj Ali Khan,0,
Qasim al-Raimi,,
Saeed al-Shehri,,
Fahd al-Qusaa,,
Malang Wazir,,
Haitham al-Yemeni,,
Ayman al-Zawahiri; Abu Khabab al-Masri; Abd Rahman al-Masri al-Maghribi; Abu Ubeidah al-Masri; Marwan al-Suri; Khalid Habib; Abdul Hadi al-Iraqi,,5

In [22]:
drone_df.groupby('country').deaths_min.count()
#drone_df.groupby('town').children.count()

country
Pakistan                       428
Pakistan-Afghanistan Border      1
Somalia                         20
Yemen                          175
Name: deaths_min, dtype: int64

In [260]:
def clean_column(my_col):
    pattern = re.compile(r'[0-9]+')
    for i in my_col:
        encoded = i.encode('ascii') 
        return map(lambda x: int(x), pattern.findall(encoded))  

import re    
string = drone_df.deaths[1].encode('ascii')
import numpy as np
pattern = re.compile(r'[0-9]+')
np.max(map(lambda x: int(x), pattern.findall(string)))

def clean_column_02(my_col):
    for i in enumerate(my_col):
        string = my_col[i].encode('ascii')
        pattern = re.compile(r'[0-9]+')
        np.max(map(lambda x: int(x), pattern.findall(string)))

In [272]:
def clean_column(my_col):
    for i in enumerate(my_col):
        a = i[1].encode('ascii')
        pattern = re.compile(r'[0-9]+')
        try:
            print np.max(map(lambda x: int(x), pattern.findall(a)))
        except:
            pass
        
map(clean_column, drone_df.deaths[1:100])

6
8
2
8
5
8
1
3
2
2
8
1
8
3
8
3
4
2
0
3
4
5
1
0
1
2
1
5
8
1
3
1
2
2
0
1
2
2
0
1
6
1
2
1
3
2
5
8
1
2
0
4
5
6
8
4
1
0
5
7
5
1
2
1
7
2
3
1
0
1
5
4
7
4
8
3
2
1
4
9
4
5
5
9
7
1
1
1
5
2
0
4
2
5
4
1
2
1
1
1
6
1
1
1
3
4
6
4
6
5
2
3
3
4
6
7
2
3
3
2
4
3
5
3
4
7
1
5
5
1
0
2
6
3
5
3
0
3
1
7
1
2
1
4
2
5
2
5
7
8
4
5
1
2
1
4
1
3
4
0
8
6
1
0
9
2
5
8
9
2
5
4
0
3
5
1
2
1
4
6
6
7
8
3
0
5
1
3
1
7
1
6
1
8
8
1
0
3
5
4
0
3
5
5
5
6
2
1
2
1
4
2
5
1
7
2
1
8
1
0
5
8
1
0
1
5
5
1
0
1
2
5
6
4
9
8
9
3
4
3
2
0
2
7
4
6
3
6
3
1
0

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [275]:
drone_df.deaths[1].encode('ascii')

'6-8'

In [274]:
map(clean_column, drone_df.deaths[1:100])

6
8
2
8
5
8
1
3
2
2
8
1
8
3
8
3
4
2
0
3
4
5
1
0
1
2
1
5
8
1
3
1
2
2
0
1
2
2
0
1
6
1
2
1
3
2
5
8
1
2
0
4
5
6
8
4
1
0
5
7
5
1
2
1
7
2
3
1
0
1
5
4
7
4
8
3
2
1
4
9
4
5
5
9
7
1
1
1
5
2
0
4
2
5
4
1
2
1
1
1
6
1
1
1
3
4
6
4
6
5
2
3
3
4
6
7
2
3
3
2
4
3
5
3
4
7
1
5
5
1
0
2
6
3
5
3
0
3
1
7
1
2
1
4
2
5
2
5
7
8
4
5
1
2
1
4
1
3
4
0
8
6
1
0
9
2
5
8
9
2
5
4
0
3
5
1
2
1
4
6
6
7
8
3
0
5
1
3
1
7
1
6
1
8
8
1
0
3
5
4
0
3
5
5
5
6
2
1
2
1
4
2
5
1
7
2
1
8
1
0
5
8
1
0
1
5
5
1
0
1
2
5
6
4
9
8
9
3
4
3
2
0
2
7
4
6
3
6
3
1
0

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

## Team Popcorn

You're a force to be reckoned with when you `read_csv` into your `movie_df` dataframe.  You are team "Popcorn".  It would be nice to know:

 - Which movies remained in the top 10 the longest
 - Which movies were good investments?
 
 Bonus:
 - Do any holidays impact sales performance or position?


_[There's a data dictionary available!](http://www.amstat.org/publications/jse/v17n1/datasets.mclaren.html)_

In [5]:
movie_df = pd.read_csv("../data/movie_weekend.csv")
movie_df.head(5)

   NUMBER             MOVIE  WEEK_NUM  WEEKEND_PER_THEATER WEEKEND_DATE
0       1  A Beautiful Mind         1                  701     12/21/01
1       1  A Beautiful Mind         2                14820     12/28/01
2       1  A Beautiful Mind         3                 8940       1/4/02
3       1  A Beautiful Mind         4                 6850      1/11/02
4       1  A Beautiful Mind         5                 5280      1/18/02

## Team Titanic

Known for it's honesty, the Titanic dataset is a very common dataset for doing classification prediction of fatalities.  For our challenge, why don't we try to focus on the latent characteristics. 

For the record, this is how much know:

![](http://www.glencoe.com/sec/math/studytools/books/0-07-829631-5/images/IQ02-003W-8228662.gif)

Certainly there is a better story to tell.

**Bonus**
 - Can you pull out titles (ie: Mr., Miss, Mrs) from the feature "Name" and assign it to a new variable? We think there could be something interesting to look at in aggregate based on titles!

In [411]:
titanic_df = pd.read_csv("../data/titanic.csv")
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,NaN,S